export const STRINGS = {
  en: {
    main: {
      welcome: "Welcome to Vremea - the forecasting app",
      tomorrow: "Tomorrow",
      highlights: "Today's highlights",
      wind: "Wind status",
      humidity: "Humidity",
      visibility: "Visibility",
      pressure: "Air pressure",
    },
    location: {
      button: "Search",
      input: "search for location",
    },
    todayForecast: {
      welcome:
        "To get started, search for a place or use your current device location",
      button: "Search for places",
      today: "Today",
    },
    weather: {
      SNOW: "Snow",
      SLEET: "Sleet",
      HAIL: "Hail",
      THUNDERSTORMS: "Thunderstorms",
      HEAVYRAIN: "Heavy rain",
      LIGHTRAIN: "Light rain",
      SHOWERS: "Showers",
      HEAVYCLOUDS: "Heavy clouds",
      LIGHTCLOUDS: "Light clouds",
      CLEAR: "Clear",
    },
    compass: {
      S: "S",
      SSW: "S-SW",
      SSE: "S-SE",
      SW: "SW",
      W: "W",
      WNW: "W-NW",
      WSW: "W-SW",
      NW: "NW",
      N: "N",
      NNW: "N-NW",
      NNE: "N-NE",
      NE: "NE",
      E: "E",
      ESE: "E-SE",
      ENE: "E-NE",
      SE: "SE",
    },
  },
  ro: {
    main: {
      welcome: "Bine ați venit la Vremea - o aplicație de prognoză meteo",
      tomorrow: "Mâine",
      highlights: "Datele de azi",
      wind: "Vânt",
      humidity: "Umiditate",
      visibility: "Vizibilitate",
      pressure: "Presiune atmosferică",
    },
    location: {
      button: "Caută",
      input: "caută un loc",
    },
    todayForecast: {
      welcome:
        "Pentru a începe, caută un loc sau folosește serviciile de localizare",
      button: "Caută un loc",
      today: "Astăzi",
    },
    weather: {
      SNOW: "Ninsoare",
      SLEET: "Lapoviță",
      HAIL: "Grindină",
      THUNDERSTORM: "Furtună",
      HEAVYRAIN: "Ploaie abundentă",
      LIGHTRAIN: "Ploaie",
      SHOWERS: "Ploaie măruntă",
      HEAVYCLOUDS: "Foarte înnorat",
      LIGHTCLOUDS: "Puțin înnorat",
      CLEAR: "Senin",
    },
    compass: {
      S: "S",
      SSW: "S-SV",
      SSE: "S-SE",
      SW: "SV",
      W: "V",
      WNW: "V-NV",
      WSW: "V-SV",
      NW: "NV",
      N: "N",
      NNW: "N-NV",
      NNE: "N-NE",
      NE: "NE",
      E: "E",
      ESE: "E-SE",
      ENE: "E-NE",
      SE: "SE",
    },
  },
};
